var comes_from = {
    big_bang: "big bang fusion",
    cosmic_rays: "cosmic rays fission",
    dying_low_mass_stars: "dying low mass stars",
    merging_neutron_stars: "merging neutron stars",
    exploding_massive_stars: "exploding massive stars",
    exploding_white_dwarfs: "exploding white dwarfs",
    man_made: "human synthesis (man made)"
};



var element_data = [
    {
        atomic_number: 1,
        name: "Hydrogen",
        symbol: "H",
        mass: 1.008,
        type: "Non Metal",
        class_type: "non-metal",
        boiling_point: -253,
        discovered: 1776,
        description: "Hydrogen is an explosive gas and also the lightest element.",
        where_its_used: "Hydrogen makes up about 90% of atoms in the entire universe. Hydrogen was used as a main fuel for the space shuttle program by NASA.",
        where_its_from: whereItComesFrom(comes_from.big_bang, comes_from.cosmic_rays)
    }, 
    {
        atomic_number: 2,
        name: "Helium",
        symbol: "He",
        mass: 4.003,
        type: "Noble Gas",
        class_type: "noble-gas",
        boiling_point: -269,
        discovered: 1895,
        description: "Helium is an inert gas and the second-lightest element.",
        where_its_used: "Helium gas is commonly known to be lighter than air, which leads to its use in weather and party balloons. It is also used as an inert shield for arc welding and to pressurize liquid fuel tanks in rockets.",
        where_its_from: whereItComesFrom(comes_from.big_bang, comes_from.exploding_massive_stars, comes_from.dying_low_mass_stars)
    }, 
    {
        atomic_number: 3,
        name: "Lithium",
        symbol: "Li",
        mass: 6.941,
        type: "Alkali Metal",
        class_type: "alkali-metal",
        boiling_point: 1347,
        discovered: 1817,
        description: "Lithium is the lightest metal and is soft and reactive.",
        where_its_used: "Lithium is known most commonly to be used in batteries. It is also used in aluminum alloys, to make cookware more durable, and most surprisingly, as a mood stabilizer for bipolar disorder.",
        where_its_from: whereItComesFrom(comes_from.dying_low_mass_stars, comes_from.big_bang, comes_from.cosmic_rays)
    }, 
    {
        atomic_number: 4,
        name: "Beryllium",
        symbol: "Be",
        mass: 9.012,
        type: "Alkaline Earth Metal",
        class_type: "alkaline-earth-metal",
        boiling_point: 2970,
        discovered: 1797,
        description: "Beryllium is a lightweight metal.",
        where_its_used: "This element is most commonly used as an alloying agent for copper. When combined, the resultant metal, beryllium copper, is used for springs and a variety of electrical applications. Due to its lightweight metal properties, it is used structurally in the aerospace industries.",
        where_its_from: whereItComesFrom(comes_from.cosmic_rays)
    }, 
    {
        atomic_number: 5,
        name: "Boron",
        symbol: "B",
        mass: 10.811,
        type: "Metalloid",
        class_type: "metalloid",
        boiling_point: 2550,
        discovered: 1808,
        description: "Boron is a hard black solid.",
        where_its_used: "Boron is used in pyrotechnics. When burned, it gives off a green color in the flame. More common uses are in boric acid and borax. You can find boron in antiseptics, washing chemicals, ceramic glazes, and eye drops.",
        where_its_from: whereItComesFrom(comes_from.cosmic_rays)
    }, 
    {
        atomic_number: 6,
        name: "Carbon",
        symbol: "C",
        mass: 12.011,
        type: "Non Metal",
        class_type: "non-metal",
        boiling_point: 4827,
        discovered: "Ancient",
        description: "Carbon can form different lattices like hard diamond or soft graphite.",
        where_its_used: "Carbon is the basis for the world's natural organic fuels such as natural gas, coal, and oil. Graphite, a strong molecular form of carbon is used for pencils, crucibles, and electrodes. Pure diamond is also entirely made out of carbon atoms.",
        where_its_from: whereItComesFrom(comes_from.exploding_massive_stars, comes_from.dying_low_mass_stars)
    }, 
    {
        atomic_number: 7,
        name: "Nitrogen",
        symbol: "N",
        mass: 14.007,
        type: "Non Metal",
        class_type: "non-metal",
        boiling_point: -196,
        discovered: 1772,
        description: "Nitrogen is a colorless gas.",
        where_its_used: "78 percent of Earth's entire atmosphere is made up of nitrogen. The element is significant to the chemical industry as it is a key nutrient in fertilizers and a key component in nitric acid, nylon, and explosive materials.",
        where_its_from: whereItComesFrom(comes_from.exploding_massive_stars, comes_from.dying_low_mass_stars)
    }, 
    {
        atomic_number: 8,
        name: "Oxygen",
        symbol: "O",
        mass: 15.999,
        type: "Non Metal",
        class_type: "non-metal",
        boiling_point: -183,
        discovered: 1774,
        description: "Oxygen is a colorless gas.",
        where_its_used: "Oxygen is the most important element to human's survival. Pure oxygen is used to treat breathing problems and make spacecraft livable. Oxygen in industry is mainly used in the manufacturing of steel and other metal alloys.",
        where_its_from: whereItComesFrom(comes_from.exploding_massive_stars)
    }, 
    {
        atomic_number: 9,
        name: "Flourine",
        symbol: "F",
        mass: 18.998,
        type: "Halogen",
        class_type: "halogen",
        boiling_point: 18.998,
        discovered: 1886,
        description: "Fluorine is a yellowish poison gas and the most reactive element.",
        where_its_used: "Fluorine is a common additive to drinking water and is used as a cleaning agent in toothpaste. In pop culture, hydrofluoric acid was used as a dissolving agent in the popular TV show 'Breaking Bad.' The chemical can dissolve glass and is used mainly as an etching compound.",
        where_its_from: whereItComesFrom(comes_from.exploding_massive_stars)
    }, 
    {
        atomic_number: 10,
        name: "Neon",
        symbol: "Ne",
        mass: 20.180,
        type: "Noble Gas",
        class_type: "noble-gas",
        boiling_point: -246,
        discovered: 1898,
        description: "Neon is an inert gas.",
        where_its_used: "Neon is the fourth most abundant element in the entire universe. By far the most prominent use of the element is used in advertising signs. When enticed with electricity, the glass commonly glows, leading to its use in the respective sign industry as well as high-voltage indicators and lasers.",
        where_its_from: whereItComesFrom(comes_from.exploding_massive_stars)
    },
    {
        atomic_number: 11,
        name: "Sodium",
        symbol: "Na",
        mass: 22.990,
        type: "Alkali Metal",
        class_type: "alkali-metal",
        boiling_point: 883,
        discovered: 1807,
        description: "Sodium is a very reactive soft metal.",
        where_its_used: "Sodium is used in streetlights to produce yellow light as well as being a component in many compounds like table salt, soda ash, borax, and baking soda.",
        where_its_from: whereItComesFrom(comes_from.exploding_massive_stars)
    },
    {
        atomic_number: 12,
        name: "Magnesium",
        symbol: "Mg",
        mass: 24.305,
        type: "Alkaline Earth Metal",
        class_type: "alkaline-earth-metal",
        boiling_point: 1090,
        discovered: 1755,
        description: "Magnesium is a lightweight metal.",
        where_its_used: "Magnesium finds many of its uses in medicine as Epsom salts, milk of magnesia, chloride, and citrate. Magnesium is also essential to both animal and plant life.",
        where_its_from: whereItComesFrom(comes_from.exploding_massive_stars)
    },
    {
        atomic_number: 13,
        name: "Aluminum",
        symbol: "Al",
        mass: 26.982,
        type: "Post Transition Metal",
        class_type: "post-transition-metal",
        boiling_point: 2467,
        discovered: 1825,
        description: "Aluminum is a lightweight non-corroding metal.",
        where_its_used: "Aluminum is a soft and malleable metal that has uses in cans and fouls, utensils, airplane and automotive parts, and other structural applications.",
        where_its_from: whereItComesFrom(comes_from.exploding_massive_stars)
    },
    {
        atomic_number: 14,
        name: "Silicon",
        symbol: "Si",
        mass: 28.086,
        type: "Metalloid",
        class_type: "metalloid",
        boiling_point: 2355,
        discovered: 1824,
        description: "Silicon is a hard metalloid.",
        where_its_used: "Silicon is used extensively in the semiconductor industry in solid-state electronics. For such applications, the silicon has to be doped with boron, gallium, phosphorus or arsenic.",
        where_its_from: whereItComesFrom(comes_from.exploding_massive_stars, comes_from.exploding_white_dwarfs)
    },
    {
        atomic_number: 15,
        name: "Phosphorus",
        symbol: "P",
        mass: 30.974,
        type: "Non Metal",
        class_type: "non-metal",
        boiling_point: 280,
        discovered: 1669,
        description: "Phosphorus is a glowing white waxy solid.",
        where_its_used: "Phosphorus is the main nutrient for organic life through phosphate compounds. It is used in fertilizers to uphold the biological phosphorus cycle. It is also used in explosive and pyrotechnics.",
        where_its_from: whereItComesFrom(comes_from.exploding_massive_stars, comes_from.exploding_white_dwarfs)
    },
    {
        atomic_number: 16,
        name: "Sulfur",
        symbol: "S",
        mass: 32.065,
        type: "Non Metal",
        class_type: "non-metal",
        boiling_point: 445,
        discovered: "Ancient",
        description: "Sulfur is a brittle yellow solid.",
        where_its_used: "Sulfur is used in gunpowder and other pyrotechnics, rubber manufacturing, and as an insecticide, fungicide, and fumigant. It can also be used to treat skin diseases, however, its prime use is in compound separation.",
        where_its_from: whereItComesFrom(comes_from.exploding_massive_stars, comes_from.exploding_white_dwarfs)
    },
    {
        atomic_number: 17,
        name: "Chlorine",
        symbol: "S",
        mass: 35.453,
        type: "Halogen",
        class_type: "halogen",
        boiling_point: -35,
        discovered: 1774,
        description: "Chlorine is a greenish poison gas.",
        where_its_used: "Chlorine is used in water treatment and as an antiseptic. During the production of papers, plastics, solvents, and textiles, large amounts of chlorine are also used.",
        where_its_from: whereItComesFrom(comes_from.exploding_massive_stars, comes_from.exploding_white_dwarfs)
    },
    {
        atomic_number: 18,
        name: "Argon",
        symbol: "Ar",
        mass: 39.948,
        type: "Noble Gas",
        class_type: "noble-gas",
        boiling_point: -186,
        discovered: 1894,
        description: "Argon is an inert gas.",
        where_its_used: "Argon is used in incandescent and fluorescent bulbs as a protective layer around the filament to keep oxygen from corroding it. It is also used as a protective shield in arc welding and semiconductor crystals.",
        where_its_from: whereItComesFrom(comes_from.exploding_massive_stars, comes_from.exploding_white_dwarfs)
    },
    {
        atomic_number: 19,
        name: "Potassium",
        symbol: "K",
        mass: 39.098,
        type: "Alkali Metal",
        class_type: "alkali-metal",
        boiling_point: 774,
        discovered: 1807,
        description: "Potassium is a soft metal and is reactive.",
        where_its_used: "Potassium is mainly used in compounds. It is combined with chlorine to produce potassium chloride which is used in fertilizers. Potassium hydroxide is also used in soaps and cleaners.",
        where_its_from: whereItComesFrom(comes_from.exploding_massive_stars, comes_from.exploding_white_dwarfs)
    },
    {
        atomic_number: 20,
        name: "Calcium",
        symbol: "Ca",
        mass: 40.078,
        type: "Alkaline Earth Metal",
        class_type: "alkaline-earth-metal",
        boiling_point: 1484,
        discovered: 1808,
        description: "Calcium is a soft metal.",
        where_its_used: "Calcium is used to prepare thorium and uranium as a reducing agent. It is also used as an alloying agent in aluminum, copper, lead, and magnesium.",
        where_its_from: whereItComesFrom(comes_from.exploding_massive_stars, comes_from.exploding_white_dwarfs)
    },
    {
        atomic_number: 21,
        name: "Scandium",
        symbol: "Sc",
        mass: 44.956,
        type: "Transition Metal",
        class_type: "transition-metal",
        boiling_point: 2832,
        discovered: 1879,
        description: "Scandium is a soft lightweight metal.",
        where_its_used: "Used heavily in mercury vapor lamps, Scandium is a key element in stadium lights. Its radioactive isotope is also used as a tracing agent.",
        where_its_from: whereItComesFrom(comes_from.exploding_massive_stars, comes_from.exploding_white_dwarfs)
    },
    {
        atomic_number: 22,
        name: "Titanium",
        symbol: "Ti",
        mass: 47.867,
        type: "Transition Metal",
        class_type: "transition-metal",
        boiling_point: 3287,
        discovered: 1791,
        description: "Titanium is the strongest lightweight metal and is heat-resistant.",
        where_its_used: "Titanium is an incredibly strong metal used in alloys with aluminum, iron, and other metals. This strong metal is used in the aerospace industry as well as engines. It can maintain its strength in thermal extremes.",
        where_its_from: whereItComesFrom(comes_from.exploding_white_dwarfs, comes_from.exploding_massive_stars)
    },
    {
        atomic_number: 23,
        name: "Vanadium",
        symbol: "V",
        mass: 50.942,
        type: "Transition Metal",
        class_type: "transition-metal",
        boiling_point: 3380,
        discovered: 1830,
        description: "Vanadium is a hard metal.",
        where_its_used: "This element is used in jet engines and aircraft components. All of its uses require it to be combined with another metal or element, such as Vanadium-gallium tape used in magnets.",
        where_its_from: whereItComesFrom(comes_from.exploding_white_dwarfs, comes_from.exploding_massive_stars)
    },
    {
        atomic_number: 24,
        name: "Chromium",
        symbol: "Cr",
        mass: 51.996,
        type: "Transition Metal",
        class_type: "transition-metal",
        boiling_point: 2672,
        discovered: 1797,
        description: "Chromium is a hard shiny metal.",
        where_its_used: "Chromium is used in stainless steel as well as in the chrome plating process. Various chromium compounds are known for their vivid colors.",
        where_its_from: whereItComesFrom(comes_from.exploding_white_dwarfs, comes_from.exploding_massive_stars)
    },
    {
        atomic_number: 25,
        name: "Manganese",
        symbol: "Mn",
        mass: 54.938,
        type: "Transition Metal",
        class_type: "transition-metal",
        boiling_point: 1962,
        discovered: 1774,
        description: "Manganese is a hard metal.",
        where_its_used: "Manganese dioxide makes up about .14% of Earth's crust. It is heavily used in batteries to keep hydrogen from forming. It is also used in glass to remove the green color present from iron compounds.",
        where_its_from: whereItComesFrom(comes_from.exploding_white_dwarfs, comes_from.exploding_massive_stars)
    },
    {
        atomic_number: 26,
        name: "Iron",
        symbol: "Fe",
        mass: 55.845,
        type: "Transition Metal",
        class_type: "transition-metal",
        boiling_point: 2750,
        discovered: "Ancient",
        description: "Iron is a medium-hard metal and has magnetic properties.",
        where_its_used: "Iron's prime use is in making steel. When steel is combined with chromium, it produces stainless steel which is resistant to corrosion.",
        where_its_from: whereItComesFrom(comes_from.exploding_white_dwarfs, comes_from.exploding_massive_stars)
    },
    {
        atomic_number: 27,
        name: "Cobalt",
        symbol: "Co",
        mass: 58.933,
        type: "Transition Metal",
        class_type: "transition-metal",
        boiling_point: 2870,
        discovered: 1735,
        description: "Cobalt is a hard metal and is magnetic.",
        where_its_used: "Cobalt is used mostly as a cancer treatment and in radiotherapy.",
        where_its_from: whereItComesFrom(comes_from.exploding_white_dwarfs, comes_from.exploding_massive_stars)
    },
    {
        atomic_number: 28,
        name: "Nickel",
        symbol: "Ni",
        mass: 58.933,
        type: "Transition Metal",
        class_type: "transition-metal",
        boiling_point: 2732,
        discovered: 1751,
        description: "Nickel is a medium-hard metal and is magnetic.",
        where_its_used: "Nickel is used in stainless steel and other anti-corrosion metal alloys. Other prominent uses include piping and tubing production as well as in the desalination process.",
        where_its_from: whereItComesFrom(comes_from.exploding_white_dwarfs, comes_from.exploding_massive_stars)
    },
    {
        atomic_number: 29,
        name: "Copper",
        symbol: "Cu",
        mass: 63.546,
        type: "Transition Metal",
        class_type: "transition-metal",
        boiling_point: 2567,
        discovered: "Ancient",
        description: "Copper is a colored metal that conducts heat and electricity well.",
        where_its_used: "Copper is one of the best conductors of electricity, which lends to its use in electronics and motors. The metal is also very thermally conductive, so it is used in radiators, A/C units, and heating systems.",
        where_its_from: whereItComesFrom(comes_from.exploding_white_dwarfs, comes_from.exploding_massive_stars)
    },
    {
        atomic_number: 30,
        name: "Zinc",
        symbol: "Zn",
        mass: 65.546,
        type: "Transition Metal",
        class_type: "transition-metal",
        boiling_point: 907,
        discovered: "Ancient",
        description: "Zinc is a non-corroding metal.",
        where_its_used: "Zinc is used as an alloying agent in brass, nickel, silver and aluminum. Paints, rubbers, cosmetics, batteries, textiles, and inks also have a significant need for the element.",
        where_its_from: whereItComesFrom(comes_from.exploding_white_dwarfs, comes_from.exploding_massive_stars)
    },
    {
        atomic_number: 31,
        name: "Gallium",
        symbol: "Ga",
        mass: 69.723,
        type: "Post Transition Metal",
        class_type: "post-transition-metal",
        boiling_point: 2403,
        discovered: 1875,
        description: "Gallium is a soft metal that has a low melting point.",
        where_its_used: "Since gallium has a low melting point, it is often used in medical thermometers as a substitute for mercury. When combined with arsenic, it is used in semiconductors, lasers, and solar panels. It can also be used in mirror manufacturing.",
        where_its_from: whereItComesFrom(comes_from.exploding_massive_stars)
    },
    {
        atomic_number: 32,
        name: "Germanium",
        symbol: "Ge",
        mass: 72.640,
        type: "Metalloid",
        class_type: "metalloid",
        boiling_point: 2830,
        discovered: 1886,
        description: "Germanium is a brittle metalloid.",
        where_its_used: "Germanium finds its uses in the semiconductor industry. When it is doped with other elements, it makes highly efficient transistors. Continuing on with its electronic uses, it is also implemented in fluorescent lamps.",
        where_its_from: whereItComesFrom(comes_from.exploding_massive_stars)
    },
    {
        atomic_number: 33,
        name: "Arsenic",
        symbol: "As",
        mass: 74.922,
        type: "Metalloid",
        class_type: "metalloid",
        boiling_point: 613,
        discovered: "Ancient",
        description: "Arsenic is a brittle metalloid.",
        where_its_used: "This element is used as a doping agent in transistors, primarily with Gallium. Many arsenic compounds are used as insecticides and poisons.",
        where_its_from: whereItComesFrom(comes_from.exploding_massive_stars)
    },
    {
        atomic_number: 34,
        name: "Selenium",
        symbol: "Se",
        mass: 78.960,
        type: "Non Metal",
        class_type: "non-metal",
        boiling_point: 685,
        discovered: 1817,
        description: "Selenium is a brittle gray solid.",
        where_its_used: "Primary uses for selenium are in the glass industry. Its properties allow it to decolorize class and make red glass as well. It is used in solar and photocells. In film photography, it is also used as a photographic toner.",
        where_its_from: whereItComesFrom(comes_from.exploding_massive_stars)
    },
    {
        atomic_number: 35,
        name: "Bromine",
        symbol: "Br",
        mass: 79.904,
        type: "Halogen",
        class_type: "halogen",
        boiling_point: 59,
        discovered: 1826,
        description: "Bromine is a dark red liquid.",
        where_its_used: "Bromine is used as a flame-retarder in plastics and electronics. It can also be used to purify and disinfect water, leading to its uses in swimming pools and hot tubs.",
        where_its_from: whereItComesFrom(comes_from.exploding_massive_stars)
    },
    {
        atomic_number: 36,
        name: "Krypton",
        symbol: "Kr",
        mass: 83.800,
        type: "Noble Gas",
        class_type: "noble-gas",
        boiling_point: -153,
        discovered: 1898,
        description: "Krypton is an inert gas.",
        where_its_used: "About .0001% of Earth's atmosphere is krypton, which makes obtaining it relatively hard. The element is used for flashes in high-speed photography as well as a conductive gas in fluorescent lights.",
        where_its_from: whereItComesFrom(comes_from.exploding_massive_stars)
    },
    {
        atomic_number: 37,
        name: "Rubidium",
        symbol: "Rb",
        mass: 85.468,
        type: "Alkali Metal",
        class_type: "alkali-metal",
        boiling_point: 688,
        discovered: 1861,
        description: "Rubidium is a soft metal that is reactive.",
        where_its_used: "Rubidium is used in vacuum tubes to remove trace gases. It also is heavily used in photocells and specialized glasses. It can be ionized easily, so it is often utilized as a propellant in spacecraft.",
        where_its_from: whereItComesFrom(comes_from.exploding_massive_stars)
    },
    {
        atomic_number: 38,
        name: "Stronium",
        symbol: "Sr",
        mass: 87.620,
        type: "Alkaline Earth Metal",
        class_type: "alkaline-earth-metal",
        boiling_point: 1384,
        discovered: 1790,
        description: "Strontium is a soft metal.",
        where_its_used: "Strontium is used in pyrotechnics to produce brilliant reds. It can also be used in ferrite magnet production and zinc refining.",
        where_its_from: whereItComesFrom(comes_from.dying_low_mass_stars, comes_from.exploding_massive_stars)
    },
    {
        atomic_number: 39,
        name: "Yttrium",
        symbol: "Y",
        mass: 88.906,
        type: "Transition Metal",
        class_type: "transition-metal",
        boiling_point: 3337,
        discovered: 1794,
        description: "Yttrium is a soft metal.",
        where_its_used: "An oxide of yttrium is used to make red phosphorus television tubes. Along with this, it is used to increase the strength in aluminum and magnesium alloys.",
        where_its_from: whereItComesFrom(comes_from.dying_low_mass_stars, comes_from.exploding_massive_stars)
    },
    {
        atomic_number: 40,
        name: "Zirconoim",
        symbol: "Zr",
        mass: 91.224,
        type: "Transition Metal",
        class_type: "transition-metal",
        boiling_point: 4377,
        discovered: 1789,
        description: "Zirconium is a non-corroding neutron-resistant metal.",
        where_its_used: "Zirconium is used as an anti-corrosion compound in pumps and valves. It does not absorb neutrons, so it is also widely used in nuclear reactors.",
        where_its_from: whereItComesFrom(comes_from.dying_low_mass_stars, comes_from.exploding_massive_stars)
    },
    {
        atomic_number: 41,
        name: "Niobium",
        symbol: "Nb",
        mass: 92.906,
        type: "Transition Metal",
        class_type: "transition-metal",
        boiling_point: 4927,
        discovered: 1801,
        description: "Niobium is a non-corroding metal with a high melting point.",
        where_its_used: "Niobium is used in stainless steel alloys. Alloys produced with Niobium are very strong and are often used in pipelines and jet engines.",
        where_its_from: whereItComesFrom(comes_from.dying_low_mass_stars, comes_from.merging_neutron_stars)
    },
    {
        atomic_number: 42,
        name: "Molybdenum",
        symbol: "Mo",
        mass: 95.940,
        type: "Transition Metal",
        class_type: "transition-metal",
        boiling_point: 4612,
        discovered: 1781,
        description: "Molybdenum is a high-melting-point metal.",
        where_its_used: "Molybdenum is used in missile and aircraft parts as well as the nuclear power industry. It can be used to refine petroleum, but its main use is as an alloying agent to refine steel.",
        where_its_from: whereItComesFrom(comes_from.dying_low_mass_stars, comes_from.merging_neutron_stars)
    },
    {
        atomic_number: 43,
        name: "Technetium",
        symbol: "Tc",
        mass: 98.000,
        type: "Transition Metal",
        class_type: "transition-metal",
        boiling_point: 4877,
        discovered: 1937,
        description: "Technetium is a radioactive element that is long-lived.",
        where_its_used: "Technetium is a synthesized element that can be used as a radioactive tracer.",
        where_its_from: whereItComesFrom(comes_from.man_made)
    },
    {
        atomic_number: 44,
        name: "Ruthenium",
        symbol: "Ru",
        mass: 101.070,
        type: "Transition Metal",
        class_type: "transition-metal",
        boiling_point: 3900,
        discovered: 1844,
        description: "Ruthenium is a hard metal that is non-corrosive.",
        where_its_used: "Ruthenium is used as a catalyst to harden metals. It is also used in electrical contacts and to color glass.",
        where_its_from: whereItComesFrom(comes_from.merging_neutron_stars, comes_from.dying_low_mass_stars)
    },
    {
        atomic_number: 45,
        name: "Rhodium",
        symbol: "Rh",
        mass: 102.906,
        type: "Transition Metal",
        class_type: "transition-metal",
        boiling_point: 3727,
        discovered: 1803,
        description: "Rhodium is a non-corroding hard shiny metal.",
        where_its_used: "Rhodium is used to manufacture electrical contacts. This use extends into catalytic converters, but its primary use is as an alloying agent. Alloys of rhodium can be used in furnaces, electrodes, and spark plugs.",
        where_its_from: whereItComesFrom(comes_from.merging_neutron_stars, comes_from.dying_low_mass_stars)
    },
    {
        atomic_number: 46,
        name: "Palladium",
        symbol: "Pd",
        mass: 106.420,
        type: "Transition Metal",
        class_type: "transition-metal",
        boiling_point: 2927,
        discovered: 1803,
        description: "Palladium is a non-corroding hard metal that readily absorbs hydrogen.",
        where_its_used: "Palladium is an important element to the catalytic conversion process. It is also used in jewelry and dental fillings.",
        where_its_from: whereItComesFrom(comes_from.merging_neutron_stars, comes_from.dying_low_mass_stars)
    },
    {
        atomic_number: 47,
        name: "Silver",
        symbol: "Ag",
        mass: 107.868,
        type: "Transition Metal",
        class_type: "transition-metal",
        boiling_point: 2212,
        discovered: "Ancient",
        description: "Silver is a soft shiny metal that is the best electrical conductor.",
        where_its_used: "Silver is used in jewelry and tableware. It is the best reflector of light known to man, although it does tarnish. It is used in soldering and brazing compounds as well as batteries.",
        where_its_from: whereItComesFrom(comes_from.merging_neutron_stars, comes_from.dying_low_mass_stars)
    },
    {
        atomic_number: 48,
        name: "Cadmium",
        symbol: "Cd",
        mass: 112.411,
        type: "Transition Metal",
        class_type: "transition-metal",
        boiling_point: 765,
        discovered: 1817,
        description: "Cadmium is a non-corroding soft metal that is toxic.",
        where_its_used: "Cadmium is poisonous, so it has few uses. It can be used to prevent corrosion or to absorb neutrons in nuclear reactors. One of its more commercial uses is in rechargeable nickel-cadmium batteries.",
        where_its_from: whereItComesFrom(comes_from.merging_neutron_stars, comes_from.dying_low_mass_stars)
    },
    {
        atomic_number: 49,
        name: "Idium",
        symbol: "In",
        mass: 114.818,
        type: "Post Transition Metal",
        class_type: "post-transition-metal",
        boiling_point: 2000,
        discovered: 1863,
        description: "Indium is a soft metal.",
        where_its_used: "Indium is primarily used as a doping agent for germanium in the transistor manufacturing process. It is also used to make highly reflective mirrors and low-melting point alloys.",
        where_its_from: whereItComesFrom(comes_from.merging_neutron_stars, comes_from.dying_low_mass_stars)
    },
    {
        atomic_number: 50,
        name: "Tin",
        symbol: "Sn",
        mass: 118.710,
        type: "Post Transition Metal",
        class_type: "post-transition-metal",
        boiling_point: 2270,
        discovered: "Ancient",
        description: "Tin is a non-corroding soft metal.",
        where_its_used: "Tin has the ability to be polished to a high degree and is not corrodible. It is mainly used to coat other metals or as an alloy in solder and pewter. Niobium-tin magnets are known for their superconducting abilities.",
        where_its_from: whereItComesFrom(comes_from.dying_low_mass_stars, comes_from.merging_neutron_stars)
    },
    {
        atomic_number: 51,
        name: "Antimony",
        symbol: "Sb",
        mass: 121.760,
        type: "Metalloid",
        class_type: "metalloid",
        boiling_point: 1750,
        discovered: "Ancient",
        description: "Antimony is a brittle metalloid.",
        where_its_used: "Antimony is mainly used in batteries, cable sheathing, and other metal products. It can be used to make flame-proof materials and paints. Ancient Egyptians used the element as black eye make-up.",
        where_its_from: whereItComesFrom(comes_from.merging_neutron_stars, comes_from.dying_low_mass_stars)
    },
    {
        atomic_number: 52,
        name: "Tellurium",
        symbol: "Te",
        mass: 127.600,
        type: "Metalloid",
        class_type: "metalloid",
        boiling_point: 990,
        discovered: 1783,
        description: "Tellurium is a brittle metalloid.",
        where_its_used: "Tellurium allows better machinability of copper and stainless steel. It is used as a basic component of cast iron and blasting caps.",
        where_its_from: whereItComesFrom(comes_from.dying_low_mass_stars, comes_from.merging_neutron_stars)
    },
    {
        atomic_number: 53,
        name: "Iodine",
        symbol: "I",
        mass: 126.905,
        type: "Halogen",
        class_type: "halogen",
        boiling_point: 184,
        discovered: 1811,
        description: "Iodine is a violet-black solid.",
        where_its_used: "Iodine is used in photographic film and as an antiseptic for wounds. The radioactive isotope iodine-131 is used to treat some thyroid diseases.",
        where_its_from: whereItComesFrom(comes_from.merging_neutron_stars, comes_from.dying_low_mass_stars)
    },
    {
        atomic_number: 54,
        name: "Xenon",
        symbol: "Xe",
        mass: 1311.293,
        type: "Noble Gas",
        class_type: "noble-gas",
        boiling_point: -103,
        discovered: 1898,
        description: "Xenon is an inert gas.",
        where_its_used: "Xenon is used in photographic flashes and arc lamps for movie sets. When pressurized into an arc lamp, it can produce UV light. It is also used for radiation detection and in X-ray counters.",
        where_its_from: whereItComesFrom(comes_from.merging_neutron_stars, comes_from.dying_low_mass_stars)
    },
    {
        atomic_number: 55,
        name: "Cesium",
        symbol: "Cs",
        mass: 132.906,
        type: "Alkali Metal",
        class_type: "alkali-metal",
        boiling_point: 678,
        discovered: 1860,
        description: "Caesium (Cesium) is a soft metal that is reactive and has the largest stable atoms.",
        where_its_used: "Caesium is used as a getter in vacuum tubes to remove trace gasses. It is also a prime element in atomic clocks as well as being a catalyst to the process of hydrogenation.",
        where_its_from: whereItComesFrom(comes_from.merging_neutron_stars, comes_from.dying_low_mass_stars)
    },
    {
        atomic_number: 56,
        name: "Barrium",
        symbol: "Ba",
        mass: 137.327,
        type: "Alkaline Earth Metal",
        class_type: "alkaline-earth-metal",
        boiling_point: 1140,
        discovered: 1808,
        description: "Barium is a soft metal that absorbs X-rays.",
        where_its_used: "Barium is used to produce a green glow in pyrotechnics. It is also used as a getter to remove gases from vacuum tubes. Compounds of barium are used as a contrast medium in X-rays.",
        where_its_from: whereItComesFrom(comes_from.dying_low_mass_stars, comes_from.merging_neutron_stars)
    },
    {
        atomic_number: 72,
        name: "Hafnium",
        symbol: "Hf",
        mass: 178.490,
        type: "Transition Metal",
        class_type: "transition-metal",
        boiling_point: 5400,
        discovered: 1923,
        description: "Hafnium is a non-corroding metal that absorbs neutrons.",
        where_its_used: "Hafnium is a good neutron absorber, so it is used in nuclear control rods in nuclear submarines. Due to its high melting point, it is also used in plasma welding torches. Hafnium oxide is used in microchips.",
        where_its_from: whereItComesFrom(comes_from.dying_low_mass_stars, comes_from.merging_neutron_stars)
    },
    {
        atomic_number: 73,
        name: "Tantalum",
        symbol: "Ta",
        mass: 180.948,
        type: "Transition Metal",
        class_type: "transition-metal",
        boiling_point: 5475,
        discovered: 1802,
        description: "Tantalum is a high-melting-point non-corroding metal.",
        where_its_used: "Tantalum is used in the electronics industry for capacitors and resistors. The metal is also used in surgical instruments because it causes no immune response.",
        where_its_from: whereItComesFrom(comes_from.merging_neutron_stars, comes_from.dying_low_mass_stars)
    },
    {
        atomic_number: 74,
        name: "Tungsten",
        symbol: "W",
        mass: 183.840,
        type: "Transition Metal",
        class_type: "transition-metal",
        boiling_point: 5660,
        discovered: 1783,
        description: "Tungsten is a highest-melting-point dense metal.",
        where_its_used: "Tungsten has the highest melting point of all metals, leading to its use as filaments in incandescent bulbs. It is also used in steels to impart strength.",
        where_its_from: whereItComesFrom(comes_from.dying_low_mass_stars, comes_from.merging_neutron_stars)
    },
    {
        atomic_number: 75,
        name: "Rhenium",
        symbol: "Re",
        mass: 186.207,
        type: "Transition Metal",
        class_type: "transition-metal",
        boiling_point: 5627,
        discovered: 1925,
        description: "Rhenium is a high-melting-point dense metal.",
        where_its_used: "Rhenium is a common catalyst in the production of high-octane gasoline. It is also used in alloys for jet engines and as filaments for mass spectrographs.",
        where_its_from: whereItComesFrom(comes_from.merging_neutron_stars, comes_from.dying_low_mass_stars)
    },
    {
        atomic_number: 76,
        name: "Osmium",
        symbol: "Os",
        mass: 190.230,
        type: "Transition Metal",
        class_type: "transition-metal",
        boiling_point: 5027,
        discovered: 1803,
        description: "Osmium is a non-corroding high-melting-point hard metal and is the densest element.",
        where_its_used: "Osmium is mainly used to make hard metal alloys. You can find it in ball point pen tips, record needles, electrical contacts, and other metal components where friction needs to be mitigated.",
        where_its_from: whereItComesFrom(comes_from.merging_neutron_stars, comes_from.dying_low_mass_stars)
    },
    {
        atomic_number: 77,
        name: "Iridium",
        symbol: "Ir",
        mass: 192.217,
        type: "Transition Metal",
        class_type: "transition-metal",
        boiling_point: 4527,
        discovered: 1803,
        description: "Iridium is a non-corroding hard metal and is also the densest element (same as Os).",
        where_its_used: "Iridium is mostly used as a hardening agent for platinum. This element is also used in fountain pen tips and compass bearings.",
        where_its_from: whereItComesFrom(comes_from.merging_neutron_stars, comes_from.dying_low_mass_stars)
    },
    {
        atomic_number: 78,
        name: "Platinum",
        symbol: "Pt",
        mass: 195.967,
        type: "Transition Metal",
        class_type: "transition-metal",
        boiling_point: 3827,
        discovered: 1735,
        description: "Platinum is a non-corroding dense metal.",
        where_its_used: "Platinum has long been used for jewelry and for its corrosion resistant properties. Its main use is in catalytic converters for automobiles.",
        where_its_from: whereItComesFrom(comes_from.merging_neutron_stars, comes_from.dying_low_mass_stars)
    },
    {
        atomic_number: 79,
        name: "Gold",
        symbol: "Au",
        mass: 196.967,
        type: "Transition Metal",
        class_type: "transition-metal",
        boiling_point: 2807,
        discovered: "Ancient",
        description: "Gold is the most malleable element, and is a dense non-tarnishing colored metal.",
        where_its_used: "Gold is one of the most coveted metals in the world. It can be shaped and sculpted and it does not tarnish.",
        where_its_from: whereItComesFrom(comes_from.merging_neutron_stars, comes_from.dying_low_mass_stars)
    },
    {
        atomic_number: 80,
        name: "Mercury",
        symbol: "Hg",
        mass: 200.590,
        type: "Transition Metal",
        class_type: "transition-metal",
        boiling_point: 357,
        discovered: "Ancient",
        description: "Mercury is a liquid metal and is toxic.",
        where_its_used: "Mercury is used to make thermometers, barometers, and other instruments. It is often used in streetlights and fluorescent lamps.",
        where_its_from: whereItComesFrom(comes_from.dying_low_mass_stars, comes_from.merging_neutron_stars)
    },
    {
        atomic_number: 81,
        name: "Thallium",
        symbol: "Tl",
        mass: 204.383,
        type: "Post Transition Metal",
        class_type: "post-transition-metal",
        boiling_point: 1457,
        discovered: 1861,
        description: "Thallium is a toxic soft metal.",
        where_its_used: "Thallium is used to form low-melting point glass. It was once used as rat poison, but it is now banned from household use.",
        where_its_from: whereItComesFrom(comes_from.dying_low_mass_stars, comes_from.merging_neutron_stars)
    },
    {
        atomic_number: 82,
        name: "Lead",
        symbol: "Pb",
        mass: 207.200,
        type: "Post Transition Metal",
        class_type: "post-transition-metal",
        boiling_point: 1740,
        discovered: "Ancient",
        description: "Lead is a dense, soft, non-corroding toxic metal.",
        where_its_used: "Lead is used as a coating for wires to protect from corrosion. Most lead is used in lead-acid batteries for automobiles.",
        where_its_from: whereItComesFrom(comes_from.dying_low_mass_stars, comes_from.merging_neutron_stars)
    },
    {
        atomic_number: 83,
        name: "Bismuth",
        symbol: "Bi",
        mass: 208.980,
        type: "Post Transition Metal",
        class_type: "post-transition-metal",
        boiling_point: 1560,
        discovered: "Ancient",
        description: "Bismuth is a brittle metal with a low melting point.",
        where_its_used: "Bismuth is usually used in fire detectors and fire extinguishment systems due to its low melting point. This has also led to its use in electrical fuses.",
        where_its_from: whereItComesFrom(comes_from.merging_neutron_stars)
    },
    {
        atomic_number: 84,
        name: "Polonium",
        symbol: "Po",
        mass: 209.000,
        type: "Metalloid",
        class_type: "metalloid",
        boiling_point: 962,
        discovered: 1898,
        description: "Polonium is a radioactive element that is long-lived.",
        where_its_used: "Polonium is used as an atomic heat source for short term use. It is also seen in anti-static brushes and in film.",
        where_its_from: whereItComesFrom(comes_from.merging_neutron_stars)
    },
    {
        atomic_number: 85,
        name: "Astatine",
        symbol: "At",
        mass: 210.000,
        type: "Halogen",
        class_type: "halogen",
        boiling_point: 337,
        discovered: 1940,
        description: "Astatine is a radioactive element that is short-lived.",
        where_its_used: "Astatine is used as a radioactive tracer and in cancer treatment.",
        where_its_from: whereItComesFrom(comes_from.merging_neutron_stars)
    },
    {
        atomic_number: 86,
        name: "Radon",
        symbol: "Rn",
        mass: 222.000,
        type: "Noble Gas",
        class_type: "noble-gas",
        boiling_point: -62,
        discovered: 1900,
        description: "Radon is a  radioactive gas that is short-lived.",
        where_its_used: "Radon is used to treat cancer. It was often produced in hospitals by pumping radon from radium and then sealing it into tubes.",
        where_its_from: whereItComesFrom(comes_from.merging_neutron_stars)
    },
    {
        atomic_number: 87,
        name: "Francium",
        symbol: "Fr",
        mass: 223.000,
        type: "Alkali Metal",
        class_type: "alkali-metal",
        boiling_point: 677,
        discovered: 1939,
        description: "Francium is a radioactive and short-lived element with atoms larger than cesium.",
        where_its_used: "The most stable isotope of francium, francium-223, has a half-life of 22 minutes. Due to its short lifespan, this element has no uses.",
        where_its_from: whereItComesFrom(comes_from.merging_neutron_stars)
    },
    {
        atomic_number: 88,
        name: "Radium",
        symbol: "Ra",
        mass: 226.000,
        type: "Alkaline Earth Metal",
        class_type: "alkaline-earth-metal",
        boiling_point: 1737,
        discovered: 1898,
        description: "Radium is a radioactive element that is long-lived.",
        where_its_used: "Radium is used as a neutron source and is also used to produce radon. One gram of radium-226 will make .0001 mL of radon each day. The element is 1,000,000 times more active than uranium.",
        where_its_from: whereItComesFrom(comes_from.merging_neutron_stars)
    },
    {
        atomic_number: 104,
        name: "Rutherfordium",
        symbol: "Rf",
        mass: 261.000,
        type: "Transition Metal",
        class_type: "transition-metal",
        boiling_point: 5500,
        discovered: 1964,
        description: "Rutherfordium is a radioactive element that is short-lived.",
        where_its_used: "No use outside research.",
        where_its_from: whereItComesFrom(comes_from.man_made)
    },
    {
        atomic_number: 105,
        name: "Dubnium",
        symbol: "Db",
        mass: 262.000,
        type: "Transition Metal",
        class_type: "transition-metal",
        boiling_point: "Unknown",
        discovered: 1967,
        description: "Dubnium is a radioactive element that is short-lived.",
        where_its_used: "No use outside research.",
        where_its_from: whereItComesFrom(comes_from.man_made)
    },
    {
        atomic_number: 106,
        name: "Seaborgium",
        symbol: "Sg",
        mass: 266.000,
        type: "Transition Metal",
        class_type: "transition-metal",
        boiling_point: "Unknown",
        discovered: 1974,
        description: "Seaborgium is a radioactive element that is short-lived.",
        where_its_used: "No use outside research.",
        where_its_from: whereItComesFrom(comes_from.man_made)
    },
    {
        atomic_number: 107,
        name: "Bohrium",
        symbol: "Bh",
        mass: 264.000,
        type: "Transition Metal",
        class_type: "transition-metal",
        boiling_point: "Unknown",
        discovered: 1981,
        description: "Bohrium is a radioactive element that is short-lived.",
        where_its_used: "No use outside research.",
        where_its_from: whereItComesFrom(comes_from.man_made)
    },
    {
        atomic_number: 108,
        name: "Hassium",
        symbol: "Hs",
        mass: 277.000,
        type: "Transition Metal",
        class_type: "transition-metal",
        boiling_point: "Unknown",
        discovered: 1984,
        description: "Hassium is a radioactive element that is short-lived.",
        where_its_used: "No use outside research.",
        where_its_from: whereItComesFrom(comes_from.man_made)
    },
    {
        atomic_number: 109,
        name: "Meitnerium",
        symbol: "Mt",
        mass: 268.000,
        type: "Transition Metal",
        class_type: "transition-metal",
        boiling_point: "Unknown",
        discovered: 1982,
        description: "Meitnerium is a radioactive element that is short-lived.",
        where_its_used: "No use outside research.",
        where_its_from: whereItComesFrom(comes_from.man_made)
    },
    {
        atomic_number: 110,
        name: "Darmstadtium",
        symbol: "Ds",
        mass: 281.000,
        type: "Transition Metal",
        class_type: "transition-metal",
        boiling_point: "Unknown",
        discovered: 1994,
        description: "Darmstadtium is a radioactive element that is short-lived.",
        where_its_used: "No use outside research.",
        where_its_from: whereItComesFrom(comes_from.man_made)
    },
    {
        atomic_number: 111,
        name: "Roentgenium",
        symbol: "Rg",
        mass: 282.000,
        type: "Transition Metal",
        class_type: "transition-metal",
        boiling_point: "Unknown",
        discovered: 1994,
        description: "Roentgenium is a radioactive element that is short-lived.",
        where_its_used: "No use outside research.",
        where_its_from: whereItComesFrom(comes_from.man_made)
    },
    {
        atomic_number: 112,
        name: "Coperncium",
        symbol: "Cn",
        mass: 285.000,
        type: "Transition Metal",
        class_type: "transition-metal",
        boiling_point: 37.58,
        discovered: 1996,
        description: "Copernicium is a radioactive element that is short-lived.",
        where_its_used: "No use outside research.",
        where_its_from: whereItComesFrom(comes_from.man_made)
    },
    {
        atomic_number: 113,
        name: "Nihonium",
        symbol: "Nh",
        mass: 286.000,
        type: "Post Transition Metal",
        class_type: "post-transition-metal",
        boiling_point: "Unknown",
        discovered: 2003,
        description: "Nihonium is a radioactive element that is short-lived.",
        where_its_used: "No use outside research.",
        where_its_from: whereItComesFrom(comes_from.man_made)
    },
    {
        atomic_number: 114,
        name: "Flerovium",
        symbol: "Fl",
        mass: 289.000,
        type: "Post Transition Metal",
        class_type: "post-transition-metal",
        boiling_point: "Unknown",
        discovered: 1998,
        description: "Flerovium is a radioactive element that is short-lived.",
        where_its_used: "No use outside research.",
        where_its_from: whereItComesFrom(comes_from.man_made)
    },
    {
        atomic_number: 115,
        name: "Moscovium",
        symbol: "Mc",
        mass: 290.000,
        type: "Post Transition Metal",
        class_type: "post-transition-metal",
        boiling_point: "Unknown",
        discovered: 2003,
        description: "Moscovium is a radioactive element that is short-lived.",
        where_its_used: "No use outside research.",
        where_its_from: whereItComesFrom(comes_from.man_made)
    },
    {
        atomic_number: 116,
        name: "Livermorium",
        symbol: "Lv",
        mass: 293.000,
        type: "Post Transition Metal",
        class_type: "post-transition-metal",
        boiling_point: "Unknown",
        discovered: 2000,
        description: "Livermorium is a radioactive element that is short-lived.",
        where_its_used: "No use outside research.",
        where_its_from: whereItComesFrom(comes_from.man_made)
    },
    {
        atomic_number: 117,
        name: "Tennessine",
        symbol: "Ts",
        mass: 294.000,
        type: "Halogen",
        class_type: "halogen",
        boiling_point: "Unknown",
        discovered: 2010,
        description: "Tennessine is a radioactive element that is short-lived.",
        where_its_used: "No use outside research.",
        where_its_from: whereItComesFrom(comes_from.man_made)
    },
    {
        atomic_number: 118,
        name: "Oganesson",
        symbol: "Og",
        mass: 294.000,
        type: "Noble Gas",
        class_type: "noble-gas",
        boiling_point: "Unknown",
        discovered: 2006,
        description: "Oganesson is a radioactive element that is short-lived. It is the heaviest element known to man (at the time of writing).",
        where_its_used: "No use outside research.",
        where_its_from: whereItComesFrom(comes_from.man_made)
    },
    {
        atomic_number: 57,
        name: "Lanthanum",
        symbol: "La",
        mass: 128.906,
        type: "Lanthanide",
        class_type: "lanthanide",
        boiling_point: 3469,
        discovered: 1839,
        description: "Lanthanum is a soft metal.",
        where_its_used: "Lanthanum is used along with rare earth elements to make arc lights for movie sets. The metal also makes up about 25% of Misch metal, which is used in flint production for lighters.",
        where_its_from: whereItComesFrom(comes_from.dying_low_mass_stars, comes_from.merging_neutron_stars)
    },
    {
        atomic_number: 58,
        name: "Cerium",
        symbol: "Ce",
        mass: 140.116,
        type: "Lanthanide",
        class_type: "lanthanide",
        boiling_point: 3257,
        discovered: 1803,
        description: "Cerium is a soft metal.",
        where_its_used: "Cerium is also used as a component of Misch metal to produce flint for lighters. It can be used as a catalyst to refine oil. Cerium oxide is also used as a component of walls in self-cleaning ovens.",
        where_its_from: whereItComesFrom(comes_from.dying_low_mass_stars, comes_from.merging_neutron_stars)
    },
    {
        atomic_number: 59,
        name: "Praseodymium",
        symbol: "Pr",
        mass: 140.908,
        type: "Lanthanide",
        class_type: "lanthanide",
        boiling_point: 3127,
        discovered: 1885,
        description: "Praseodymium is a soft metal.",
        where_its_used: "Praseodymium is used to make yellow glass goggles for welders. Praseodymium is also used in flint lighter products. Its main use, however, is to color glass and enamels.",
        where_its_from: whereItComesFrom(comes_from.merging_neutron_stars, comes_from.dying_low_mass_stars)
    },
    {
        atomic_number: 60,
        name: "Neodymium",
        symbol: "Nd",
        mass: 144.240,
        type: "Lanthanide",
        class_type: "lanthanide",
        boiling_point: 3127,
        discovered: 1885,
        description: "Neodymium is a soft metal.",
        where_its_used: "Neodymium is used to make flint for lighters and is a component of specialized welder's goggles. It can also be used to make powerful magnets.",
        where_its_from: whereItComesFrom(comes_from.dying_low_mass_stars, comes_from.merging_neutron_stars)
    },
    {
        atomic_number: 61,
        name: "Promethium",
        symbol: "Pm",
        mass: 145.000,
        type: "Lanthanide",
        class_type: "lanthanide",
        boiling_point: 3000,
        discovered: 1945,
        description: "Promethium is a radioactive element that is long-lived.",
        where_its_used: "Promethium is used mainly for research in radiation. It can be used in nuclear batteries and as a light source for signals. Researchers believe that it could soon be used in portable x-ray machines.",
        where_its_from: whereItComesFrom(comes_from.man_made)
    },
    {
        atomic_number: 62,
        name: "Samarium",
        symbol: "Sm",
        mass: 150.360,
        type: "Lanthanide",
        class_type: "lanthanide",
        boiling_point: 1900,
        discovered: 1879,
        description: "Samarium is a soft metal.",
        where_its_used: "Samarium is used as a catalyst for dehydration and dehydrogenation of ethanol fuels. It can also be used to absorb infrared light rays and in the treatment of cancer.",
        where_its_from: whereItComesFrom(comes_from.merging_neutron_stars, comes_from.dying_low_mass_stars)
    },
    {
        atomic_number: 63,
        name: "Europium",
        symbol: "Eu",
        mass: 151.964,
        type: "Lanthanide",
        class_type: "lanthanide",
        boiling_point: 1597,
        discovered: 1901,
        description: "Europium is a soft metal.",
        where_its_used: "Europium is a good absorber of neutrons, so it is often used in nuclear reactors. One of its compounds is also used in the production of red phosphorus in television sets.",
        where_its_from: whereItComesFrom(comes_from.merging_neutron_stars, comes_from.dying_low_mass_stars)
    },
    {
        atomic_number: 64,
        name: "Gadolinium",
        symbol: "Gd",
        mass: 157.250,
        type: "Lanthanide",
        class_type: "lanthanide",
        boiling_point: 3233,
        discovered: 1880,
        description: "Gadolinium is a soft metal that is the best neutron absorber and is magnetic.",
        where_its_used: "Gadolinium is often used in applications where microwaves are present. It can also be used in green phosphor television tubes. The element is magnetic, which has led to its use in MRI machines.",
        where_its_from: whereItComesFrom(comes_from.merging_neutron_stars, comes_from.dying_low_mass_stars)
    },
    {
        atomic_number: 65,
        name: "Terbium",
        symbol: "Tb",
        mass: 158.925,
        type: "Lanthanide",
        class_type: "lanthanide",
        boiling_point: 3041,
        discovered: 1843,
        description: "Terbium is a soft metal.",
        where_its_used: "Terbium is used as a stabilizer of high-temperature fuel cells. Its alloys are also used in electronic devices and as magnetic field indicators.",
        where_its_from: whereItComesFrom(comes_from.merging_neutron_stars, comes_from.dying_low_mass_stars)
    },
    {
        atomic_number: 66,
        name: "Dysprosium",
        symbol: "Dy",
        mass: 162.500,
        type: "Lanthanide",
        class_type: "lanthanide",
        boiling_point: 2562,
        discovered: 1886,
        description: "Dysprosium is a soft metal.",
        where_its_used: "When combined with rare earth elements, Dysprosium is used as a laser material. It can also be used in nuclear reactor rods.",
        where_its_from: whereItComesFrom(comes_from.merging_neutron_stars, comes_from.dying_low_mass_stars)
    },
    {
        atomic_number: 67,
        name: "Holmium",
        symbol: "Ho",
        mass: 164.930,
        type: "Lanthanide",
        class_type: "lanthanide",
        boiling_point: 2720,
        discovered: 1867,
        description: "Holmium is a soft metal.",
        where_its_used: "Holmium is used in the production of magnets as a flux concentrator. It is also used as a yellow or red color in cubic zirconia manufacturing.",
        where_its_from: whereItComesFrom(comes_from.merging_neutron_stars, comes_from.dying_low_mass_stars)
    },
    {
        atomic_number: 68,
        name: "Erbium",
        symbol: "Er",
        mass: 167.259,
        type: "Lanthanide",
        class_type: "lanthanide",
        boiling_point: 2510,
        discovered: 1842,
        description: "Erbium is a soft metal.",
        where_its_used: "Erbium is a good neutron absorber, leading to its use in nuclear control rods. It can also be used to reduce the hardness of metals along with applications in amps and lasers.",
        where_its_from: whereItComesFrom(comes_from.merging_neutron_stars, comes_from.dying_low_mass_stars)
    },
    {
        atomic_number: 69,
        name: "Thulium",
        symbol: "Tm",
        mass: 168.934,
        type: "Lanthanide",
        class_type: "lanthanide",
        boiling_point: 1727,
        discovered: 1879,
        description: "Thulium is a soft metal.",
        where_its_used: "Thulium is the least naturally-occurring element on earth. This soft metal is very expensive and has no commercial applications.",
        where_its_from: whereItComesFrom(comes_from.merging_neutron_stars, comes_from.dying_low_mass_stars)
    },
    {
        atomic_number: 70,
        name: "Ytterbium",
        symbol: "Yb",
        mass: 173.040,
        type: "Lanthanide",
        class_type: "lanthanide",
        boiling_point: 1466,
        discovered: 1878,
        description: "Ytterbium is a soft metal.",
        where_its_used: "Ytterbium is believed to be useable in grain refinement within steel. Other than this plausible use, no other uses have been found.",
        where_its_from: whereItComesFrom(comes_from.merging_neutron_stars, comes_from.dying_low_mass_stars)
    },
    {
        atomic_number: 71,
        name: "Lutetium",
        symbol: "Lu",
        mass: 174.967,
        type: "Lanthanide",
        class_type: "lanthanide",
        boiling_point: 3315,
        discovered: 1907,
        description: "Lutetium is a soft metal and is the densest and hardest rare earth metal.",
        where_its_used: "Lutetium is very rare and high in price. When refined, it can be used in the petroleum cracking process. There are few other commercial applications.",
        where_its_from: whereItComesFrom(comes_from.merging_neutron_stars)
    },
    {
        atomic_number: 89,
        name: "Actinium",
        symbol: "Ac",
        mass: 227.000,
        type: "Actinide",
        class_type: "actinide",
        boiling_point: 3200,
        discovered: 1899,
        description: "Actinium is a radioactive element that is long-lived.",
        where_its_used: "Actinium is used in medicine for radio-immunotherapy. It is only found in uranium ore, which makes it very expensive. One ton of uranium is equivalent to 1/10th of a gram of actinium.",
        where_its_from: whereItComesFrom(comes_from.merging_neutron_stars)
    },
    {
        atomic_number: 90,
        name: "Thorium",
        symbol: "Th",
        mass: 232.038,
        type: "Actinide",
        class_type: "actinide",
        boiling_point: 4790,
        discovered: 1829,
        description: "Thorium is a radioactive element that is long-lived.",
        where_its_used: "Thorium is used to coat filaments in incandescent bulbs. It can be used as nuclear fuel through fission.",
        where_its_from: whereItComesFrom(comes_from.merging_neutron_stars)
    },
    {
        atomic_number: 91,
        name: "Protactinium",
        symbol: "Pa",
        mass: 231.036,
        type: "Actinide",
        class_type: "actinide",
        boiling_point: "Unknown",
        discovered: 1913,
        description: "Protactinium is a radioactive element that is long-lived.",
        where_its_used: "There are currently no uses for protactinium due to its relative rarity.",
        where_its_from: whereItComesFrom(comes_from.merging_neutron_stars)
    },
    {
        atomic_number: 92,
        name: "Uranium",
        symbol: "U",
        mass: 238.029,
        type: "Actinide",
        class_type: "actinide",
        boiling_point: 3818,
        discovered: 1789,
        description: "Uranium is a radioactive element that is long-lived.",
        where_its_used: "Uranium generates heat for nuclear power reactors and produces the material needed for nuclear weapons. It is also used as a colorant for glass.",
        where_its_from: whereItComesFrom(comes_from.merging_neutron_stars)
    },
    {
        atomic_number: 93,
        name: "Neptunium",
        symbol: "Np",
        mass: 237.000,
        type: "Actinide",
        class_type: "actinide",
        boiling_point: 3902,
        discovered: 1940,
        description: "Neptunium is a radioactive element that is long-lived.",
        where_its_used: "Neptunium does not have any known uses.",
        where_its_from: whereItComesFrom(comes_from.merging_neutron_stars)
    },
    {
        atomic_number: 94,
        name: "Plutonium",
        symbol: "Pu",
        mass: 244.000,
        type: "Actinide",
        class_type: "actinide",
        boiling_point: 3235,
        discovered: 1940,
        description: "Plutonium is a radioactive element that is long-lived.",
        where_its_used: "Plutonium is used as a nuclear fuel and in nuclear weapons.",
        where_its_from: whereItComesFrom(comes_from.merging_neutron_stars)
    },
    {
        atomic_number: 95,
        name: "Americium",
        symbol: "Am",
        mass: 243.000,
        type: "Actinide",
        class_type: "actinide",
        boiling_point: 2607,
        discovered: 1944,
        description: "Americium is a radioactive element that is long-lived.",
        where_its_used: "Americium is used in smoke detectors and is a portable source of gamma rays.",
        where_its_from: whereItComesFrom(comes_from.man_made)
    },
    {
        atomic_number: 96,
        name: "Curium",
        symbol: "Cm",
        mass: 247.000,
        type: "Actinide",
        class_type: "actinide",
        boiling_point: "Unknown",
        discovered: 1944,
        description: "Curium is a radioactive element that is long-lived.",
        where_its_used: "Curium is mainly used for research, but it could produce more nuclear energy per gram than plutonium.",
        where_its_from: whereItComesFrom(comes_from.man_made)
    },
    {
        atomic_number: 97,
        name: "Berkelium",
        symbol: "Bk",
        mass: 247.000,
        type: "Actinide",
        class_type: "actinide",
        boiling_point: "Unknown",
        discovered: 1949,
        description: "Berkelium is a radioactive element that is long-lived.",
        where_its_used: "Berkelium has no uses due to its rarity.",
        where_its_from: whereItComesFrom(comes_from.man_made)
    },
    {
        atomic_number: 98,
        name: "Californium",
        symbol: "Cf",
        mass: 251.000,
        type: "Actinide",
        class_type: "actinide",
        boiling_point: "Unknown",
        discovered: 1950,
        description: "Californium is a radioactive element that is long-lived.",
        where_its_used: "Californium is a strong neutron emitter. It is used in metal detectors for silver and gold. It also can be used to identify oil layers underground and detect metal fatigue in aerospace applications.",
        where_its_from: whereItComesFrom(comes_from.man_made)
    },
    {
        atomic_number: 99,
        name: "Einsteinium",
        symbol: "Es",
        mass: 252.000,
        type: "Actinide",
        class_type: "actinide",
        boiling_point: "Unknown",
        discovered: 1952,
        description: "Einsteinium is a radioactive element that is short-lived.",
        where_its_used: "No use outside research.",
        where_its_from: whereItComesFrom(comes_from.man_made)
    },
    {
        atomic_number: 100,
        name: "Fermium",
        symbol: "Fm",
        mass: 257.000,
        type: "Actinide",
        class_type: "actinide",
        boiling_point: "Unknown",
        discovered: 1952,
        description: "Fermium is a radioactive element that is short-lived.",
        where_its_used: "No use outside research.",
        where_its_from: whereItComesFrom(comes_from.man_made)
    },
    {
        atomic_number: 101,
        name: "Mendelevium",
        symbol: "Md",
        mass: 258.000,
        type: "Actinide",
        class_type: "actinide",
        boiling_point: "Unknown",
        discovered: 1955,
        description: "Mendelevium is a radioactive element that is short-lived.",
        where_its_used: "No use outside research.",
        where_its_from: whereItComesFrom(comes_from.man_made)
    },
    {
        atomic_number: 102,
        name: "Nobelium",
        symbol: "No",
        mass: 259.000,
        type: "Actinide",
        class_type: "actinide",
        boiling_point: "Unknown",
        discovered: 1958,
        description: "Nobelium is a radioactive element that is short-lived.",
        where_its_used: "No use outside research.",
        where_its_from: whereItComesFrom(comes_from.man_made)
    },
    {
        atomic_number: 103,
        name: "Lawrencium",
        symbol: "Lr",
        mass: 262.000,
        type: "Actinide",
        class_type: "actinide",
        boiling_point: "Unknown",
        discovered: 1961,
        description: "Lawrencium is a radioactive element that is short-lived.",
        where_its_used: "No use outside research.",
        where_its_from: whereItComesFrom(comes_from.man_made)
    },
];


function whereItComesFrom(...args){
    let str = args[0];
    for(let i = 0; i < args.length; i++){
        if(i > 0){
            if(i < args.length - 1){
                str += ", " + args[i];
            } else {
                str += " & " + args[i];
            }
        }
    }
    str = str.charAt(0).toUpperCase() + str.slice(1);
    str += ".";
    return str;
}
